### ISSUE TITLE
compare with kubeflow

### ISSUE THREAD

**Issue by merlinzone** [IntelAI/nauta#1]
what is the difference between nauta and kubeflow？ which one should I choose

**Comment by adam-marek** [comment]
It mostly depends on what your data science and devops teams need. Nauta is designed to be an ‘easy button’ for teams of data scientists sharing HW resources - it doesn’t assume the user knows anything about Kubernetes, and aims to keep their experience as close to working on a dedicated workstation as possible.

**Comment by walidshaari** [comment]
doesn't Nauta build on top of kubeflow?

**Comment by adam-marek** [comment]
Nauta includes components from a number of OSS projects - including Kubeflow.

**Comment by AdamTumi** [comment]
Question answered. Closing this issue.
