### ISSUE TITLE
how to set transparent proxy

### ISSUE THREAD

**Issue by shixinlishixinli** [IntelAI/nauta#13]
i set ENV http_proxy and https_proxy of dockerfile. the docker can download , but there are also something wrong while build the nauta. 
i can successfully run go build in another dockerfile . i have no idea why this one is failed . i am looking forward your reply

Step 31/33 : RUN  go build -o /loader main.go
 ---> Running in 003b4d5cae2e
# github.com/NervanaSystems/carbon/applications/loader/vendor/github.com/docker/go-connections/sockets
vendor/github.com/docker/go-connections/sockets/sockets.go:35:26: dialer.DialContext undefined (type proxy.Dialer has no field or method DialContext)
vendor/github.com/docker/go-connections/sockets/sockets_unix.go:24:28: undefined: context

**Comment by ajoskowski** [comment]
Hi @shixinlishixinli,

Yesterday we fixed this problem by https://github.com/IntelAI/nauta/commit/aa39db264985b21378856a8cd3fdbdf2654f904b

Please pull new changes from develop branch and try again.

**Comment by shixinlishixinli** [comment]
thank you for your relpy . this bug is solved . but there are another bug while building the nauta.

fatal: [local]: FAILED! => {"changed": false, "msg": "Failed to connect to storage.googleapis.com at port 443: [Errno 101] Network is unreachable"}

**Comment by shixinlishixinli** [comment]
i have successful build nauta.
firstly ,set" ENV https_proxy=https://10.7.211.16:912""ENV http_proxy=http://10.7.211.16:911" in all Dockerfile .
secondly,set "npm config set proxy http://username:password@server:port""npm config set https-proxy http://username:pawword@server:port"
then, set "RUN curl -s -x 10.7.211.16:911 https://packages.cloud.google.com/apt/doc/apt-key.gpg | ap\
t-key add -"
finally, try to download helm.tar.gz by myself and move it into correct path.
