### ISSUE TITLE
i can not install nauta successfully

### ISSUE THREAD

**Issue by shixinlishixinli** [IntelAI/nauta#14]
hello i have successfully build the nauta . but there are some bugs while i try to install nauta.
the inventory.yaml and config,yaml is as follows

[inventory.txt](https://github.com/IntelAI/nauta/files/3206207/inventory.txt)
[config.txt](https://github.com/IntelAI/nauta/files/3206208/config.txt)

TASK [verification/pre : [platform] Fail if test failed] ******************************************************************************************************
Wednesday 22 May 2019  00:46:37 -0700 (0:00:00.039)       0:00:00.200 *********
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Master group is not defined in inventory"}
TASK [kubectl-info : Get nodes descriptions] ******************************************************************************************************************
Wednesday 22 May 2019  00:46:39 -0700 (0:00:00.636)       0:00:00.706 *********
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["/home/lisas/nauta/bin/Linux/amd64/kubectl", "describe", "--all-namespaces", "nodes"], "delta": "0:00:00.040610", "end": "2019-05-22 00:46:39.311990", "msg": "non-zero return code", "rc": 1, "start": "2019-05-22 00:46:39.271380", "stderr": "The connection to the server localhost:8080 was refused - did you specify the right host or port?", "stderr_lines": ["The connection to the server localhost:8080 was refused - did you specify the right host or port?"], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/home/lisas/nauta/diagnose/diagnose.retry

i have no idea how to solve it . and i am looking forward to your reply.

**Comment by pmilewsk** [comment]
Hello shixinlishixinli,

I suppose you have followed the documentation. We had a bug in the https://github.com/IntelAI/nauta/blob/develop/docs/installation-and-configuration/Inventory_Tasks/IT.md

Please delete asterisk ('*') from master and worker lines. It should look like this:

> [master]
> [worker]

Documentation has been updated and it will be merged soon to the develop branch.

Thank You,
Piotr Milewski

**Comment by shixinlishixinli** [comment]
hi milewski
Your help is very useful. but there are anothor bugs while i try to install nauta. could you please give me your inventory.yaml and config,yaml. so I can correctly understand  how to generate inventory.yaml and config,yaml. i was a little confused about the documentation.

TASK [verification/node-access : [platform] Check if admin user is accessible] ********************************************************************************
Wednesday 22 May 2019  02:07:20 -0700 (0:00:00.879)       0:00:09.051 *********
fatal: [master-0]: FAILED! => {"changed": false, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
fatal: [worker-0]: FAILED! => {"changed": false, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

NO MORE HOSTS LEFT ********************************************************************************************************************************************
        to retry, use: --limit @/home/lisas/nauta/platform/nauta.retry

PLAY RECAP ****************************************************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0
master-0                   : ok=30   changed=0    unreachable=0    failed=1
worker-0                   : ok=30   changed=0    unreachable=0    failed=1

**Comment by pmilewsk** [comment]
Hi shixinlishixinli,

You have to add your user to sudoers with passwordless option. 
1. Login as a root
2. run visudo
3. add your user like this example:
yourusername ALL=(ALL:ALL) NOPASSWD: ALL
4. rerun the script.

Best Regards,
Piotr Milewski

**Comment by pmilewsk** [comment]
Hello,

it seems that you have resolved the issue with previous comment. 
Can I close the ticket?

Best regards,
Piotr Milewski

**Comment by shixinlishixinli** [comment]
hello 

thank you for your reply , i have solved this issue.

best
Lisa shi
