### ISSUE TITLE
Unsupported parameters for (apt) module: disable_plugin, disablerepo, enablerepo

### ISSUE THREAD

**Issue by shixinlishixinli** [IntelAI/nauta#15]
I try to install nauta but there are some bugs.

 fatal: [master-0]: FAILED! => {"ansible_facts": {"pkg_mgr": "apt"}, "changed": false, "msg": "Unsupported parameters for (apt) module: disable_plugin, disablerepo, enablerepo Supported parameters include: allow_unauthenticated, autoclean, autoremove, cache_valid_time, deb, default_release, dpkg_options, force, force_apt_get, install_recommends, only_upgrade, package, purge, state, update_cache, upgrade"}
fatal: [worker-0]: FAILED! => {"ansible_facts": {"pkg_mgr": "apt"}, "changed": false, "msg": "Unsupported parameters for (apt) module: disable_plugin, disablerepo, enablerepo Supported parameters include: allow_unauthenticated, autoclean, autoremove, cache_valid_time, deb, default_release, dpkg_options, force, force_apt_get, install_recommends, only_upgrade, package, purge, state, update_cache, upgrade"}

**inventory.yaml**

[master]
master-0 ansible_ssh_host=10.241.98.56 ansible_ssh_user=lisas ansible_ssh_pass=intel.123 internal_interface=eth0 external_interface=lo local_data_device=/dev/\
sda1

[worker]
worker-0 ansible_ssh_host=10.238.154.70 ansible_ssh_user=lisas ansible_ssh_pass=intel.123 internal_interface=eno1 external_interface=lo

**config.yaml**
proxy:
  http_proxy: http://10.7.211.16/911
  ftp_proxy: ftp://10.7.211.16/911
  https_proxy: https://10.7.211.16/911
  no_proxy: localhost

Looking forward to your reply

best
lisa shi

**Comment by pmilewsk** [comment]
Hello Lisa,
You are trying to install the platform on ubuntu or any other debian distribution of linux which is not supported.

There are requirements for the host:
https://github.com/IntelAI/nauta/blob/develop/docs/installation-and-configuration/Target_Host_Requirements/THR.md

You can use Centos7.

Best Regards,
Piotr Milewski

**Comment by shixinlishixinli** [comment]
hi piotr

thank you for your help . but this tutorial (https://github.com/IntelAI/nauta/blob/develop/docs/installation-and-configuration/Installer_System_Requirements/ISR.md) says i can use ubuntu1604 to install nauta.

best
lisa shi

**Comment by pmilewsk** [comment]
Hi Lisa,

You can install Nauta from ubuntu 16.04 as the topic say - it is Installer system requirements - however the system underneath nauta must be Centos 7 or RHEL.

Best Regards,
Piotr Milewski

**Comment by shixinlishixinli** [comment]
hi Milewski


I'm a little confused. Do you mean that master must be installed on centos, and worker can be installed on Ubuntu or centos?

best
lisa shi

**Comment by pmilewsk** [comment]
Hi Lisa,

You can use only Centos/RHEL for nauta installation (where Nauta land). You can ubuntu as jumpbox/installer host.

Best Regards,
Piotr Milewski

**Comment by pmilewsk** [comment]
Hi Lisa,

is this issue resolved or you need further assistance?

Best regards,
Piotr Milewski

**Comment by pmilewsk** [comment]
Hello,

This ticket will be closed in 5 days if there will not be any action from user.

Best Regards,
Piotr Milewski
