### ISSUE TITLE
Compilation Issues with Nauta

### ISSUE THREAD

**Issue by nfawad** [IntelAI/nauta#17]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):BUG REPORT

**Cluster configuration details:**
- **Cloud provider or hardware configuration:**
using skylake cpu with 512 Gig Ram and 6152 Gold 22 core processors.

- **Operating system:** (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):
OS: Ubuntu 16.04 LTS
- **Nauta version and commit:** (`nctl version`)(`git rev-parse --short HEAD`):
Using the latest committed version.
[k8s_installer_build.log](https://github.com/IntelAI/nauta/files/3299547/k8s_installer_build.log)

**Nauta component related with bug:** (`build system/installer/nctl(cli)/dashboard/documentation/k8s/any of nauta container`)

**What is the current behavior?**

**What is the expected behavior?**

**Steps to reproduce:**
* 
*

**Anything else do we need to know**:

Build file attached.

**Comment by jcchr** [comment]
The problem was caused by incorrect version of a Docker used to build Nauta. In our Dockerfiles we use features that are properly handled by since 17.05 version of Docker - so this version (or newer) is required.
