### ISSUE TITLE
Tiller instance is not ready

### ISSUE THREAD

**Issue by y-yas** [IntelAI/nauta#18]
hello
attempting to install nauta fails with an error.

TASK [applications : [platform] Wait for at least one tiller instances to get ready] *******************************************************************
Friday 13 September 2019  13:21:24 +0900 (0:00:00.280)       0:02:40.789 ******
FAILED - RETRYING: [platform] Wait for at least one tiller instances to get ready (60 retries left).
FAILED - RETRYING: [platform] Wait for at least one tiller instances to get ready (59 retries left).
.
.
.
FAILED - RETRYING: [platform] Wait for at least one tiller instances to get ready (3 retries left).
FAILED - RETRYING: [platform] Wait for at least one tiller instances to get ready (2 retries left).
FAILED - RETRYING: [platform] Wait for at least one tiller instances to get ready (1 retries left).
fatal: [master-0]: FAILED! => {"attempts": 60, "changed": false, "cmd": "kubectl --namespace=kube-system get ds tiller -o jsonpath='{.status.numberReady}'", "delta": "0:00:00.127966", "end": "2019-09-13 13:22:36.301711", "rc": 0, "start": "2019-09-13 13:22:36.173745", "stderr": "", "stderr_lines": [], "stdout": "0", "stdout_lines": ["0"]}

NO MORE HOSTS LEFT *************************************************************************************************************************************
        to retry, use: --limit @/usr/local/src/nauta-install-2/platform/nauta.retry

i have no idea how to solve it.  an anyone tell me how to solve it?
I'm sorry if I'm clumsy because I'm using git for the first time.

**Comment by mzylowski** [comment]
Hello,

Sorry for delayed answer.

Is this GCP installation or some private environment?

Any chance to paste here some tiller logs from the platform?
```
kubectl logs -n nauta <tiller pod name here>
```
Seems to some hang during tiller configuration.

If possible, please attach installation log files (from logs directory).

**Comment by y-yas** [comment]
hello

thank you for your reploy.

I will close it because I am deploying a new environment. 
Since another problem occurred in Build, I will consult separately.

**Comment by y-yas** [comment]
hello,

I used tar.gz that was built yesterday, but a Tiller error occurred in the same way.
I want to run kubectl logs -n nauta <tiller pod name here>.  Where can I find the tiller pod name?

thanks,

**Comment by y-yas** [comment]
hello,

during install nauta, An error related to tiller occurred.
could you teach me how to solve it?

TASK [applications : [platform] Apply tiller release] **********************************************************************************************************************************************
Wednesday 09 October 2019  11:37:01 +0900 (0:00:00.489)       0:02:41.413 *****
fatal: [nauta-master]: FAILED! => {"changed": false, "cmd": "kubectl apply -f /root/kubernetes/apps/tiller.yml", "delta": "0:00:00.122755", "end": "2019-10-09 11:37:01.539311", "msg": "non-zero return code", "rc": 1, "start": "2019-10-09 11:37:01.416556", "stderr": "The Service \"tiller\" is invalid: spec.clusterIP: Invalid value: \"10.3.23.235\": field is immutable", "stderr_lines": ["The Service \"tiller\" is invalid: spec.clusterIP: Invalid value: \"10.3.23.235\": field is immutable"], "stdout": "serviceaccount/tiller unchanged\nclusterrolebinding.rbac.authorization.k8s.io/tiller unchanged\ndaemonset.apps/tiller unchanged\ndeployment.apps/tiller-deploy unchanged", "stdout_lines": ["serviceaccount/tiller unchanged", "clusterrolebinding.rbac.authorization.k8s.io/tiller unchanged", "daemonset.apps/tiller unchanged", "deployment.apps/tiller-deploy unchanged"]}

NO MORE HOSTS LEFT *********************************************************************************************************************************************************************************
        to retry, use: --limit @/usr/local/src/platform/nauta.retry

PLAY RECAP *****************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0
nauta-master               : ok=553  changed=21   unreachable=0    failed=1
worker01                   : ok=163  changed=6    unreachable=0    failed=0
worker02                   : ok=163  changed=6    unreachable=0    failed=0


<BR>
<BR>
<BR>
<BR>
<BR>
<BR>

The pod is not created.
kubectl get node
NAME                            STATUS     ROLES    AGE   VERSION
nauta-master.node.ai-ex.local   NotReady   Master   65m   v1.15.3
worker01.node.ai-ex.local       NotReady   Worker   65m   v1.15.3
worker02.node.ai-ex.local       NotReady   Worker   65m   v1.15.3

kubectl get pod
No resources found.


thanks,
yas

**Comment by y-yas** [comment]
hello,

during install nauta in a private environment, An error related to tiller occurred.
could you teach me how to solve it?

TASK [applications : [platform] Apply tiller release] **********************************************************************************************************************************************
Wednesday 09 October 2019 11:37:01 +0900 (0:00:00.489) 0:02:41.413 *****
fatal: [nauta-master]: FAILED! => {"changed": false, "cmd": "kubectl apply -f /root/kubernetes/apps/tiller.yml", "delta": "0:00:00.122755", "end": "2019-10-09 11:37:01.539311", "msg": "non-zero return code", "rc": 1, "start": "2019-10-09 11:37:01.416556", "stderr": "The Service "tiller" is invalid: spec.clusterIP: Invalid value: "10.3.23.235": field is immutable", "stderr_lines": ["The Service "tiller" is invalid: spec.clusterIP: Invalid value: "10.3.23.235": field is immutable"], "stdout": "serviceaccount/tiller unchanged\nclusterrolebinding.rbac.authorization.k8s.io/tiller unchanged\ndaemonset.apps/tiller unchanged\ndeployment.apps/tiller-deploy unchanged", "stdout_lines": ["serviceaccount/tiller unchanged", "clusterrolebinding.rbac.authorization.k8s.io/tiller unchanged", "daemonset.apps/tiller unchanged", "deployment.apps/tiller-deploy unchanged"]}

NO MORE HOSTS LEFT *********************************************************************************************************************************************************************************
to retry, use: --limit @/usr/local/src/platform/nauta.retry

PLAY RECAP *****************************************************************************************************************************************************************************************
localhost : ok=4 changed=0 unreachable=0 failed=0
nauta-master : ok=553 changed=21 unreachable=0 failed=1
worker01 : ok=163 changed=6 unreachable=0 failed=0
worker02 : ok=163 changed=6 unreachable=0 failed=0






The pod is not created.
kubectl get node
NAME STATUS ROLES AGE VERSION
nauta-master.node.ai-ex.local NotReady Master 65m v1.15.3
worker01.node.ai-ex.local NotReady Worker 65m v1.15.3
worker02.node.ai-ex.local NotReady Worker 65m v1.15.3

kubectl get pod
No resources found.

thanks,
yas

**Comment by mateusz-ciesielski** [comment]
Hi,
it looks like for some reason, tiller service already existed in kube-system namespace before `Apply tiller release` step was executed. Probably this tiller service is a remnant of previous Nauta installations, or installations of other helm packages in the cluster. In order to check if it is the real cause, you can check services in kube-system namespace by running:
```
kubectl get services -n kube-system
```

You should see then a list similar to this one:
```
NAME                                        TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)          AGE
heapster                                    ClusterIP   10.4.61.34    <none>        80/TCP           13d
nauta-k8s-platform-dashboard                ClusterIP   10.4.26.82    <none>        80/TCP           13d
nauta-k8s-platform-ingress                  ClusterIP   10.4.0.15     <none>        80/TCP,443/TCP   13d
nauta-k8s-platform-ingress-defaultbackend   ClusterIP   10.4.215.37   <none>        80/TCP           13d
nauta-k8s-platform-skydns                   ClusterIP   10.4.0.10     <none>        53/UDP,53/TCP    13d
tiller                                      ClusterIP   10.4.0.11     <none>        44134/TCP        13d
```

If there is a `tiller` service on your list, like on the example above, try to delete it by running following command:
```
kubectl delete service -n kube-system tiller
```
and run installation again - hopefully installer will not run in such condition twice.

If removing tiller service does not help, you could try reinstalling nauta by running:
```
./installer.sh nauta-uninstall
```
and following installation procedure again (steps with `./installer.sh install`).

Please comment if that does not help, or if any other error will occur, and thanks for checking out Nauta.

Thanks,
Mateusz

**Comment by y-yas** [comment]
hello,

thank you for your reply.
it was installed again after the tiller service stopped.
Another error has occurred. (Same as the first ...)

TASK [applications : [platform] Wait for at least one tiller instances to get ready] ***************************************************************************************************************
Thursday 10 October 2019  10:01:01 +0900 (0:00:00.318)       0:02:41.083 ******
FAILED - RETRYING: [platform] Wait for at least one tiller instances to get ready (60 retries left).
FAILED - RETRYING: [platform] Wait for at least one tiller instances to get ready (59 retries left).
FAILED - RETRYING: [platform] Wait for at least one tiller instances to get ready (58 retries left).
.
.
.
FAILED - RETRYING: [platform] Wait for at least one tiller instances to get ready (2 retries left).
FAILED - RETRYING: [platform] Wait for at least one tiller instances to get ready (1 retries left).
fatal: [nauta-master]: FAILED! => {"attempts": 60, "changed": false, "cmd": "kubectl --namespace=kube-system get ds tiller -o jsonpath='{.status.numberReady}'", "delta": "0:00:00.068978", "end": "2019-10-10 18:58:18.572643", "rc": 0, "start": "2019-10-10 18:58:18.503665", "stderr": "", "stderr_lines": [], "stdout": "0", "stdout_lines": ["0"]}

NO MORE HOSTS LEFT *********************************************************************************************************************************************************************************
        to retry, use: --limit @/usr/local/src/platform/nauta.retry

PLAY RECAP *****************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0
nauta-master               : ok=551  changed=7    unreachable=0    failed=1
worker01                   : ok=161  changed=4    unreachable=0    failed=0
worker02                   : ok=161  changed=4    unreachable=0    failed=0



Do you need kubectl logs?
   kubectl logs -n nauta _Tiller pod_

But there is no namespace nauta.
kubectl get pods -A
NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
kube-system   kube-proxy-nauta-master.node.ai-ex.local   1/1     Running   0          5m19s
kube-system   kube-proxy-worker01.node.ai-ex.local       1/1     Running   0          4m52s
kube-system   kube-proxy-worker02.node.ai-ex.local       1/1     Running   0          4m56s

thanks,
yas

**Comment by y-yas** [comment]
hello,
A log was obtained.  Is it useful for solve?

kubectl get pod -A
NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
kube-system   kube-proxy-nauta-master.node.ai-ex.local   1/1     Running   0          10m
kube-system   kube-proxy-worker01.node.ai-ex.local       1/1     Running   0          9m58s
kube-system   kube-proxy-worker02.node.ai-ex.local       1/1     Running   0          10m



kubectl logs -n kube-system  kube-proxy-nauta-master.node.ai-ex.local
Flag --resource-container has been deprecated, This feature will be removed in a later release.
W1010 04:43:29.593567       6 server.go:216] WARNING: all flags other than --config, --write-config-to, and --cleanup are deprecated. Please begin using a config file ASAP.
W1010 04:43:29.601614       6 proxier.go:513] Failed to load kernel module ip_vs with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W1010 04:43:29.602334       6 proxier.go:513] Failed to load kernel module ip_vs_rr with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W1010 04:43:29.603027       6 proxier.go:513] Failed to load kernel module ip_vs_wrr with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W1010 04:43:29.603672       6 proxier.go:513] Failed to load kernel module ip_vs_sh with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
I1010 04:43:29.610851       6 server_others.go:143] Using iptables Proxier.
I1010 04:43:29.611538       6 server.go:534] Version: v1.15.3
I1010 04:43:29.612524       6 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_max' to 131072
I1010 04:43:29.612541       6 conntrack.go:52] Setting nf_conntrack_max to 131072
I1010 04:43:29.612579       6 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_established' to 86400
I1010 04:43:29.612604       6 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_close_wait' to 3600
I1010 04:43:29.612911       6 config.go:96] Starting endpoints config controller
I1010 04:43:29.612932       6 controller_utils.go:1029] Waiting for caches to sync for endpoints config controller
I1010 04:43:29.612996       6 config.go:187] Starting service config controller
I1010 04:43:29.613001       6 controller_utils.go:1029] Waiting for caches to sync for service config controller
I1010 04:43:29.713125       6 controller_utils.go:1036] Caches are synced for service config controller
I1010 04:43:29.713125       6 controller_utils.go:1036] Caches are synced for endpoints config controller

thanks,
yas

**Comment by mateusz-ciesielski** [comment]
Hi,
it looks like we have to see why tiller instance does not want to start. We can get tiller logs by doing following steps:
1. Run `kubectl get pods -n kube-system`
You should see then output similar to this one:
```
[root@nervana-dev-04-02 ~]# kubectl get pods -n kube-system
NAME                                                         READY   STATUS    RESTARTS   AGE
kube-proxy-nervana-dev-03-04.node.infra.nauta                1/1     Running   0          6h26m
kube-proxy-nervana-dev-04-02.node.infra.nauta                1/1     Running   0          6h26m
kube-proxy-nervana-dev-07-04.node.infra.nauta                1/1     Running   0          6h26m
nauta-k8s-platform-dashboard-65897f969d-4rr8k                1/1     Running   0          6h25m
nauta-k8s-platform-flannel-ens4-jfk76                        1/1     Running   0          6h25m
nauta-k8s-platform-flannel-ens4-mlxlw                        1/1     Running   0          6h25m
nauta-k8s-platform-flannel-ens4-q8hwf                        1/1     Running   0          6h25m
nauta-k8s-platform-heapster-7b54978c45-hntbq                 1/1     Running   0          6h25m
nauta-k8s-platform-ingress-defaultbackend-745dfc9bf6-bvg68   1/1     Running   0          6h25m
nauta-k8s-platform-ingress-rpplt                             1/1     Running   0          6h24m
nauta-k8s-platform-netfilter-fix-ddww6                       1/1     Running   0          6h24m
nauta-k8s-platform-netfilter-fix-gvrv2                       1/1     Running   0          6h24m
nauta-k8s-platform-skydns-bncjc                              3/3     Running   0          6h24m
tiller-89fnw                                                 1/1     Running   0          6h26m
```

2. From the output of `kubectl get pods -n kube-system` we can get the name of tiller pod - in my case it is `tiller-89fnw` , in your case it will also be named similar (starting with `tiller-...`).

3. Now we have name of the tiller pod, so we can check how it is doing by running following commands:
`kubectl describe pod -n kube-system <name of your tiller pod>`
`kubectl logs -n kube-system <name of your tiller pod>`

There should be some hints why tiller does not work in output of these commands, please post the output here.

Again, thanks for reply and sorry for troubles with installation (there are many things that could go wrong, unfortunately). We are working on improvements of installation process, so similar issues will hopefully stop haunting us.

Thanks,
Mateusz

**Comment by y-yas** [comment]
hi,

thank you for your reply.

Run kubectl get pods -n kube-system. but not display like start tiller....


Command execution result is,
[root@nauta-master ~]# kubectl get pods -n kube-system
NAME                                       READY   STATUS    RESTARTS   AGE
kube-proxy-nauta-master.node.ai-ex.local   1/1     Running   0          7h33m
kube-proxy-worker01.node.ai-ex.local       1/1     Running   0          7h32m
kube-proxy-worker02.node.ai-ex.local       1/1     Running   0          7h32m
[root@nauta-master ~]#

Thank you for your reply and help!!!
thanks,
yas

**Comment by mateusz-ciesielski** [comment]
Hi,
it looks like Kubernetes already removed this pod, that's why it is not on the list anymore :( We can try to run this command:
```
kubectl describe daemonset -n kube-system tiller
```
 and check if there will be some hints about the root cause in the output.

Thanks,
Mateusz

**Comment by y-yas** [comment]
hi,

Command execution result is,

[root@nauta-master ~]# kubectl describe daemonset -n kube-system tiller
Name:           tiller
Selector:       app=helm,name=tiller
Node-Selector:  master=True
Labels:         app=helm
                name=tiller
Annotations:    deprecated.daemonset.template.generation: 1
                kubectl.kubernetes.io/last-applied-configuration:
                  {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"app":"helm","name":"tiller"},"name":"tiller","namespace...
Desired Number of Nodes Scheduled: 0
Current Number of Nodes Scheduled: 0
Number of Nodes Scheduled with Up-to-date Pods: 0
Number of Nodes Scheduled with Available Pods: 0
Number of Nodes Misscheduled: 0
Pods Status:  0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app=helm
                    name=tiller
  Service Account:  tiller
  Containers:
   tiller:
    Image:       registry.service.ai-ex.local:5000/core/tiller:v2.11.0
    Ports:       44134/TCP, 44135/TCP
    Host Ports:  44134/TCP, 44135/TCP
    Liveness:    http-get http://:44135/liveness delay=1s timeout=1s period=10s #success=1 #failure=3
    Readiness:   http-get http://:44135/readiness delay=1s timeout=1s period=10s #success=1 #failure=3
    Environment:
      TILLER_NAMESPACE:    kube-system
      TILLER_HISTORY_MAX:  0
    Mounts:                <none>
  Volumes:                 <none>
Events:                    <none>
[root@nauta-master ~]#

thanks,
yas

**Comment by mateusz-ciesielski** [comment]
Hi, 
this line looks suspicious:
```
Desired Number of Nodes Scheduled: 0
```
it looks like tiller daemonset does not even want to create a pod. Only reason I can think of now is that something is wrong with node labels.
Can you run:
`kubectl describe node nauta-master.node.ai-ex.local` ?
In the output, there should be a section called labels, looking similar to this one:
```
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    gpu=False
                    iface=ens4
                    ingress=True
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=nervana-dev-01-03.node.infra.nauta
                    kubernetes.io/os=linux
                    master=True
                    nauta-release-version-1-1-0-ent-20191007171352=True
                    node-role.kubernetes.io/Master=True
```

If you do not see `master=True` or `node-role.kubernetes.io/Master=True` in your output, please run following commands:
```
 kubectl label nodes nauta-master.node.ai-ex.local master=True
 kubectl label nodes nauta-master.node.ai-ex.local Master=True
 kubectl label nodes nauta-master.node.ai-ex.local node-role.kubernetes.io/Master=True
```
and check if tiller started by running previous commands (`kubectl get pods -n kube-system` and `kubectl describe daemonset -n kube-system tiller`). If tiller started after this change, I think it would be best to run installation again (or uninstall Nauta and then retry installation).

If these labels were already set, please post the output of `kubectl describe node nauta-master.node.ai-ex.local`, so we'll think of other solution.

Thanks,
Mateusz

**Comment by y-yas** [comment]
hi,

i can see master=true in Label section.


[root@nauta-master ~]# kubectl describe node nauta-master.node.ai-ex.local
Name:               nauta-master.node.ai-ex.local
Roles:              Master
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    gpu=False
                    iface=ens224
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=nauta-master.node.ai-ex.local
                    kubernetes.io/os=linux
                    **master=True**
                    node-role.kubernetes.io/Master=True



Since master = true, the result of kubectl get pods -n kube-system does not change.

[root@nauta-master ~]# kubectl get pods -n kube-system
NAME                                       READY   STATUS    RESTARTS   AGE
kube-proxy-nauta-master.node.ai-ex.local   1/1     Running   0          8h
kube-proxy-worker01.node.ai-ex.local       1/1     Running   0          8h
kube-proxy-worker02.node.ai-ex.local       1/1     Running   0          8h


thanks,
yas

**Comment by mateusz-ciesielski** [comment]
Hi,
Could you post full output of `kubectl describe node nauta-master.node.ai-ex.local` ? Only other cause I can think of now is that there is some strange issue with taints/tolerations on the master node.

Thanks,
Mateusz

**Comment by y-yas** [comment]
hi,

full output is,


[root@nauta-master ~]# kubectl describe node nauta-master.node.ai-ex.local
Name:               nauta-master.node.ai-ex.local
Roles:              Master
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    gpu=False
                    iface=ens224
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=nauta-master.node.ai-ex.local
                    kubernetes.io/os=linux
                    master=True
                    node-role.kubernetes.io/Master=True
Annotations:        volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Thu, 10 Oct 2019 13:43:07 +0900
Taints:             node.kubernetes.io/not-ready:NoSchedule
Unschedulable:      false
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Thu, 10 Oct 2019 22:04:59 +0900   Thu, 10 Oct 2019 13:43:07 +0900   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Thu, 10 Oct 2019 22:04:59 +0900   Thu, 10 Oct 2019 13:43:07 +0900   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Thu, 10 Oct 2019 22:04:59 +0900   Thu, 10 Oct 2019 13:43:07 +0900   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            False   Thu, 10 Oct 2019 22:04:59 +0900   Thu, 10 Oct 2019 13:43:07 +0900   KubeletNotReady              runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Addresses:
  InternalIP:  192.168.23.33
  Hostname:    nauta-master.node.ai-ex.local
Capacity:
 cpu:                2
 ephemeral-storage:  36678148Ki
 hugepages-1Gi:      0
 hugepages-2Mi:      0
 memory:             16432436Ki
 pods:               210
Allocatable:
 cpu:                1
 ephemeral-storage:  33802581141
 hugepages-1Gi:      0
 hugepages-2Mi:      0
 memory:             15330036Ki
 pods:               210
System Info:
 Machine ID:                 776de0b44b7c423eb18bfd57789e2a96
 System UUID:                51731E42-04FD-1C20-9FAE-AF532BB8994E
 Boot ID:                    9ea3f502-b8f2-4364-9634-f0a7a9fdfcd8
 Kernel Version:             3.10.0-862.el7.x86_64
 OS Image:                   CentOS Linux 7 (Core)
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://18.9.9
 Kubelet Version:            v1.15.3
 Kube-Proxy Version:         v1.15.3
Non-terminated Pods:         (1 in total)
  Namespace                  Name                                        CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                  ----                                        ------------  ----------  ---------------  -------------  ---
  kube-system                kube-proxy-nauta-master.node.ai-ex.local    100m (10%)    0 (0%)      128m (0%)        0 (0%)         8h
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests    Limits
  --------           --------    ------
  cpu                100m (10%)  0 (0%)
  memory             128m (0%)   0 (0%)
  ephemeral-storage  0 (0%)      0 (0%)
Events:              <none>

thanks,
yas

**Comment by mateusz-ciesielski** [comment]
Hi,
now I think we are getting closer to the root cause:
```
Taints: node.kubernetes.io/not-ready:NoSchedule
```
means, that Kubernetes thinks, that master node is not ready.

Another suspicious entry is:
```
Ready False Thu, 10 Oct 2019 22:04:59 +0900 Thu, 10 Oct 2019 13:43:07 +0900 KubeletNotReady runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
```
which indicates that there is some issue with Kubernetes networking.

There are quite many possible cases why network did not set up properly, but it seems that it is most likely caused by using incorrect interfaces in the Nauta inventory file.

Nauta inventory file is described here:
https://github.com/intelai/nauta/blob/develop/docs/installation-and-configuration/Inventory_Tasks/IT.md

Can you post inventory file that you used during installation, and output of `ifconfig` command (run this command on master node) here? Maybe there is something wrong with configuration of interfaces, and we should be able to fix it by comparing inventory file with output of this command.

Thanks,
Mateusz

**Comment by y-yas** [comment]
hi,

I think nw interface settings are correct.


[root@nauta-master ~]# nmcli d
DEVICE       TYPE      STATE     CONNECTION
ens192       ethernet  接続済み  ens192
docker0      bridge    接続済み  docker0
ens224       ethernet  接続済み  ens224
vethabc053b  ethernet  管理無し  --
lo           loopback  管理無し  --


[root@nauta-master ~]# nmcli d show ens192
GENERAL.DEVICE:                         ens192
GENERAL.TYPE:                           ethernet
GENERAL.HWADDR:                         00:50:56:9E:F8:3B
GENERAL.MTU:                            1500
GENERAL.STATE:                          100 (接続済み)
GENERAL.CONNECTION:                     ens192
GENERAL.CON-PATH:                       /org/freedesktop/NetworkManager/ActiveConnection/5
WIRED-PROPERTIES.CARRIER:               オン
IP4.ADDRESS[1]:                         10.3.23.33/24
IP4.GATEWAY:                            10.3.23.254
IP4.ROUTE[1]:                           dst = 10.3.23.0/24, nh = 0.0.0.0, mt = 100
IP4.ROUTE[2]:                           dst = 0.0.0.0/0, nh = 10.3.23.254, mt = 100
IP4.DNS[1]:                             10.3.23.12
IP6.ADDRESS[1]:                         fe80::aeb9:502d:35d0:20c6/64
IP6.ADDRESS[2]:                         fe80::b9d5:e9ef:eb73:40f3/64
IP6.GATEWAY:                            --
IP6.ROUTE[1]:                           dst = ff00::/8, nh = ::, mt = 256, table=255
IP6.ROUTE[2]:                           dst = fe80::/64, nh = ::, mt = 256
IP6.ROUTE[3]:                           dst = fe80::/64, nh = ::, mt = 100

[root@nauta-master ~]# nmcli d show ens224
GENERAL.DEVICE:                         ens224
GENERAL.TYPE:                           ethernet
GENERAL.HWADDR:                         00:50:56:9E:0F:8C
GENERAL.MTU:                            1500
GENERAL.STATE:                          100 (接続済み)
GENERAL.CONNECTION:                     ens224
GENERAL.CON-PATH:                       /org/freedesktop/NetworkManager/ActiveConnection/7
WIRED-PROPERTIES.CARRIER:               オン
IP4.ADDRESS[1]:                         192.168.23.33/24
IP4.GATEWAY:                            --
IP4.ROUTE[1]:                           dst = 192.168.23.0/24, nh = 0.0.0.0, mt = 101
IP6.ADDRESS[1]:                         fe80::a74e:3695:2623:3868/64
IP6.GATEWAY:                            --
IP6.ROUTE[1]:                           dst = ff00::/8, nh = ::, mt = 256, table=255
IP6.ROUTE[2]:                           dst = fe80::/64, nh = ::, mt = 256
IP6.ROUTE[3]:                           dst = fe80::/64, nh = ::, mt = 101


The inventory file is created like this.
[root@nauta-install ~]# cat ~/inventory.yml
[master]
nauta-master ansible_ssh_host=10.3.23.33 ansible_ssh_user=root ansible_ssh_pass=Vmware1! internal_interface=ens224 external_interface=ens192 local_data_device=/dev/sdb1

[worker]
worker01 ansible_ssh_host=10.3.23.41 ansible_ssh_user=root ansible_ssh_pass=Vmware1! internal_interface=ens224 external_interface=ens192
worker02 ansible_ssh_host=10.3.23.42 ansible_ssh_user=root ansible_ssh_pass=Vmware1! internal_interface=ens224 external_interface=ens192


thanks,
yas

**Comment by mateusz-ciesielski** [comment]
Hi, 
Yes, your inventory looks good, so this isn't this problem... Please give us some time to think about this issue, we'll also try to replicate this error. I'll provide an update tomorrow.

In the meantime, this issue: https://github.com/kubernetes/kubeadm/issues/1031 describes a similar problem. Could you post output of the following command: `cat /etc/cni/net.d/10-flannel.conflist` ?

It should look like this:
```
{
  "name": "cbr0",
  "plugins": [
    {
      "type": "flannel",
      "delegate": {
        "hairpinMode": true,
        "isDefaultGateway": true
      }
    },
    {
      "type": "portmap",
      "capabilities": {
        "portMappings": true
      }
    }
  ]
}
```

thanks, 
Mateusz

**Comment by y-yas** [comment]
hi,
Should I run this command on Master Node?
The file doesn't seem to exist.
The same is true for installer server.

[root@nauta-master ~]# cat /etc/cni/net.d/10-flannel.conflist
cat: /etc/cni/net.d/10-flannel.conflist: そのようなファイルやディレクトリはありません

thanks,
yas

**Comment by mateusz-ciesielski** [comment]
Hi,
Yes, if that file does not exist on Master Node, it indicates a problem with Nauta's kubelet network package, so the problem most probably lies on the installer side. I suspect that `nauta-uninstall` is deleting too many things under some circumstances... We'll try to find a solution tomorrow, sorry for inconvenience, and thank you for all responses.

thanks,
Mateusz

**Comment by y-yas** [comment]
hi,
thank you for your help.

Re-install OS of master and worker, and changing some settings of config file and succeeded in checking Tiller service.

```
TASK [applications : [platform] Wait for at least one tiller instances to get ready] ************************************************************************************************************

Friday 11 October 2019  10:02:13 +0900 (0:00:00.342)       0:02:51.567 ********
ok: [nauta-master]


```
There was also a 10-flannel.conflist file.

```
[root@nauta-master ~]# cat /etc/cni/net.d/10-flannel.conflist
{
  "name": "cbr0",
  "plugins": [
    {
      "type": "flannel",
      "delegate": {
        "hairpinMode": true,
        "isDefaultGateway": true
      }
    },
    {
      "type": "portmap",
      "capabilities": {
        "portMappings": true
      }
    }
  ]
}
```
The network configuration was suspicious, so I changed the IP address listed in the configuration file and succeeded.  Since the IP address was changed several times during the installation, the setting may have been left somewhere. . .

However, since a helm error occurred after that, I will contact you in another case. 


thanks,
yas
