### ISSUE TITLE
Build Faild

### ISSUE THREAD

**Issue by y-yas** [IntelAI/nauta#19]
Hello,
during "make k8s-installer-build" command, it failed and stopped in the middle. 
Can you teach me how to solve it?

my environment is,
OS
ubuntu18.04.3 LTS (Bionic Beaver) 

CPU
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xsaves arat pku ospke md_clear flush_l1d arch_capabilities

HDD
available over 100GB

Tuesday 08 October 2019  15:26:09 +0900 (0:00:00.469)       0:06:57.883 *******
===============================================================================
container-build : Wait for task shared/centos ------------------------------------------------------------------------------------------- 256.79s
container-build : Wait for task shared/centos/build-go ---------------------------------------------------------------------------------- 106.31s
prepare : Start registry container -------------------------------------------------------------------------------------------------------- 7.22s
Gathering Facts --------------------------------------------------------------------------------------------------------------------------- 1.58s
container-build : Build image shared/centos as 127.0.0.1:32791/shared/centos:7.6.1810 ----------------------------------------------------- 1.19s
container-build : Build image shared/build/rpm/python2-pip as 127.0.0.1:32791/shared/build/rpm/python2-pip:8.1.2 -------------------------- 1.14s
container-build : Build image shared/build/rpm/containerd-io as 127.0.0.1:32791/shared/build/rpm/containerd-io:1.2 ------------------------ 1.14s
container-build : Build image shared/build/rpm/nginx as 127.0.0.1:32791/shared/build/rpm/nginx:1.13.9 ------------------------------------- 1.13s
container-build : Build image shared/build/metrics as 127.0.0.1:32791/shared/build/metrics:0.0.1 ------------------------------------------ 1.13s
container-build : Build image shared/build/consul as 127.0.0.1:32791/shared/build/consul:v1.1.0 ------------------------------------------- 1.13s
container-build : Build image shared/build/rpm/docker-ce as 127.0.0.1:32791/shared/build/rpm/docker-ce:18.09 ------------------------------ 1.13s
container-build : Build image shared/build/rpm/docker-distribution as 127.0.0.1:32791/shared/build/rpm/docker-distribution:2.6.2 ---------- 1.13s
container-build : Build image shared/centos/build-go as 127.0.0.1:32791/shared/centos/build-go:1.10.2 ------------------------------------- 1.13s
container-build : Build image shared/run/tensorflow/py3.6 as 127.0.0.1:32791/shared/run/tensorflow/py3.6:py3 ------------------------------ 1.12s
container-build : Build image shared/run/tensorflow/py2.7 as 127.0.0.1:32791/shared/run/tensorflow/py2.7:py2 ------------------------------ 1.12s
container-build : Build image shared/build/rpm/container-selinux as 127.0.0.1:32791/shared/build/rpm/container-selinux:2.68 --------------- 1.12s
container-build : Build image shared/build/rpm/docker-ce-cli as 127.0.0.1:32791/shared/build/rpm/docker-ce-cli:18.09 ---------------------- 1.11s
Cleanup registry container ---------------------------------------------------------------------------------------------------------------- 0.47s
prepare : Create docker registry directories ---------------------------------------------------------------------------------------------- 0.40s
container-build : Build all images -------------------------------------------------------------------------------------------------------- 0.29s
Makefile:9: recipe for target 'build' failed
make[4]: *** [build] Error 2
make[4]: ディレクトリ '/usr/local/src/nauta/tools/container-build' から出ます
Makefile:197: recipe for target '/usr/local/src/nauta/tools/.workspace/tools/1.0.0-oss-20191008061852/tools/shared.tar.gz' failed
make[3]: *** [/usr/local/src/nauta/tools/.workspace/tools/1.0.0-oss-20191008061852/tools/shared.tar.gz] Error 2
make[3]: ディレクトリ '/usr/local/src/nauta/tools' から出ます
Makefile:71: recipe for target 'tools-release' failed
make[2]: *** [tools-release] Error 2
make[2]: ディレクトリ '/usr/local/src/nauta' から出ます
Makefile:57: recipe for target 'k8s-installer-build-wrapped' failed
make[1]: *** [k8s-installer-build-wrapped] Error 2
make[1]: ディレクトリ '/usr/local/src/nauta' から出ます
Makefile:63: recipe for target 'k8s-installer-build' failed
make: *** [k8s-installer-build] Error 2

**Comment by mzylowski** [comment]
Hello,
There should be failed ansible task somewhere above. (Please check log file and search for failed=1). Please attach part related with failed task.

Thanks,
Michal

**Comment by y-yas** [comment]
hi, Michal

I think the search results are here.

Tuesday 08 October 2019  16:47:43 +0900 (0:00:00.026)       0:00:01.847 ******* 
=============================================================================== 
Gathering Facts --------------------------------------------------------------------------------------------------------------------------- 0.53s
cpu-validation : Get CPU flags ------------------------------------------------------------------------------------------------------------ 0.19s
gather-info : Get docker version (docker version) ----------------------------------------------------------------------------------------- 0.17s
gather-info : Get physical memory status (free -h) ---------------------------------------------------------------------------------------- 0.12s
gather-info : Get CPU info (cat /proc/cpuinfo) -------------------------------------------------------------------------------------------- 0.12s
gather-info : Get disk usage stats (df -h) ------------------------------------------------------------------------------------------------ 0.12s
gather-info : Get avaible block devices (lsblk) ------------------------------------------------------------------------------------------- 0.12s
gather-info : Get Nauta commit ID (git rev-parse HEAD) ------------------------------------------------------------------------------------ 0.12s
gather-info : Print physical memory status ------------------------------------------------------------------------------------------------ 0.04s
gather-info : List available devices ------------------------------------------------------------------------------------------------------ 0.04s
gather-info : Print Nauta commit ID ------------------------------------------------------------------------------------------------------- 0.04s
gather-info : Print disk usage stats ------------------------------------------------------------------------------------------------------ 0.04s
cpu-validation : Intersect required flags with flags avaible on CPU ----------------------------------------------------------------------- 0.04s
gather-info : Print CPU info -------------------------------------------------------------------------------------------------------------- 0.04s
gather-info : Print docker version -------------------------------------------------------------------------------------------------------- 0.03s
cpu-validation : fail --------------------------------------------------------------------------------------------------------------------- 0.02s
make[2]: ディレクトリ '/usr/local/src/nauta/tools/initializers/platform' から出ます
make[2]: ディレクトリ '/usr/local/src/nauta' に入ります
make[3]: ディレクトリ '/usr/local/src/nauta/tools' に入ります
make[4]: ディレクトリ '/usr/local/src/nauta/tools/container-build' に入ります
make[4]: 警告: jobserver が利用不可: 今回は -j1 を使います. 親 make ルールに `+' を追加しましょう.
/usr/local/src/nauta/tools/.workspace/container/1.0.0-oss-20191008074731/shared




thanks,
yas

**Comment by mzylowski** [comment]
Hello,
You run into issue already fixed but not yet promoted to main branch.
I prepared a branch for You called 'y-yas'. Please trigger build procedure from this branch.

**Comment by y-yas** [comment]
hello,

thank you mzylowski!　Build complete!
I will install it tomorrow.

Tuesday 08 October 2019  18:33:05 +0900 (0:00:00.772)       0:02:09.452 *******
===============================================================================
finalize : Create package ----------------------------------------------------------------------------------------------------------------------------------------------------- 105.04s
finalize : Unpack deployer bins ------------------------------------------------------------------------------------------------------------------------------------------------ 22.44s
Remove build dir ---------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.77s
Gathering Facts ----------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.54s
finalize : Ensure release directories exists ------------------------------------------------------------------------------------------------------------------------------------ 0.38s
finalize : Copy all deployer files ---------------------------------------------------------------------------------------------------------------------------------------------- 0.21s
make[4]: ディレクトリ '/usr/local/src/nauta/tools/finalizers/release' から出ます
make[3]: ディレクトリ '/usr/local/src/nauta/tools' から出ます
make[2]: ディレクトリ '/usr/local/src/nauta' から出ます
make[2]: ディレクトリ '/usr/local/src/nauta' に入ります
make[2]: ディレクトリ '/usr/local/src/nauta' から出ます
make[1]: ディレクトリ '/usr/local/src/nauta' から出ます


thanks,
yas

**Comment by mzylowski** [comment]
Issue is fixed by https://github.com/IntelAI/nauta/commit/b80ec5ea0f3640af448bf42ef31c1bb1ef8f7010 now on master branch. Removing 'y-yas' branch.
