### ISSUE TITLE
roadmap query

### ISSUE THREAD

**Issue by walidshaari** [IntelAI/nauta#3]
Will Nauta be just for Intel Xeon CPUs? what does it take to extend it to other CPUs, GPUs, and FPGA (BrainWave on Azure)?

**Comment by nqn** [comment]
Hi there!

Nothing prevents intrinsically prevents Nauta from supporting accelerators. Intel is currently working on adding support for Intel’s accelerators, but of course we’d love the community to add support for others

**Comment by AdamTumi** [comment]
Question answered. Closing that issue.
