### ISSUE TITLE
Need to correct TensorFlow version in requirements to install on bare metal.

### ISSUE THREAD

**Issue by nparkstar** [IntelAI/nauta#31]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

I think 
/nauta/nauta-containers/openvino-mo/requirements.txt
needs to be modified as below in order to build on bare metal because TensorFlow Version 1.15 does not support Linux OS out of google cloud.

_tensorflow==1.15.2 --> tensorflow==1.14.0_

I wish you check it.

**Comment by mateusz-ciesielski** [comment]
Hi,
there was an issue with Tensorflow installation in OpenVino model optimizer image, but it was caused by too old version of pip in that image. https://github.com/IntelAI/nauta/pull/32 PR will fix that, without the need of downgrading Tensorflow version to 1.14.0.
