### ISSUE TITLE
Question about exp submit.

### ISSUE THREAD

**Issue by nparkstar** [IntelAI/nauta#40]
Hello, 
I want know about experiment submit.
When I submit the experiment to reuse as the same name the below message appears.

-----------------------------------------------------------------------------------------------
Problems during submitting experiment:  experiment with name: horovod-pod already exist!
-----------------------------------------------------------------------------------------------

Should I name a experiment newly always I submit even though same training?

I appreciate your help always.

**Comment by mateusz-ciesielski** [comment]
Hi,
you can either submit an experiment with a new name using `--name` parameter, e.g. :
```
nctl experiment submit --name horovod-pod-2 <path to the experiment's script>
```
or submit an experiment without defining a new name, like:
```
nctl experiment submit <path to the experiment's script>
```
If you don't pass `--name` parameter to the submit command, nctl should automatically generate a name for the experiment, e.g.:
```bash
# Submit first experiment
nctl experiment submit --name horovod-pod horovod.py # creates experiment horovod-pod
# Submit second experiment
nctl experiment submit -horovod.py # creates experiment horovod-pod-1
# Submit third experiment
nctl experiment submit -horovod.py # creates experiment horovod-pod-2
```

I'll try to clarify experiment's naming in the docs, this mechanism doesn't seem to be described in the documentation right now.
