### ISSUE TITLE
Build error: pull access denied for nauta/shared/build/metrics

### ISSUE THREAD

**Issue by micossow** [IntelAI/nauta#7]
I'm trying to build nauta on Ubuntu 18.04
commit cca02d93c6fa0ac0718d16d818373281f796d3a2

`make k8s-installer-build` finishes with error

```
TASK [container-build : Wait for task nauta/batch-inference] ********************************************************************************************************************************************************************************
Thursday 07 March 2019  15:27:39 +0100 (0:01:18.479)       0:27:04.823 ********
fatal: [local]: FAILED! => {"ansible_job_id": "666420320773.24313", "attempts": 1, "changed": false, "finished": 1, "msg": "Error building nauta/nauta/batch-inference - code: None, message: pull access denied for nauta/shared/build/metrics, repository does not exist or may require 'docker login', logs: ['Step 1/11 : ARG METRICS_IMAGE=metrics-image', '\\n', 'Step 2/11 : ARG BASE_IMAGE=python:3.6.8', '\\n', 'Step 3/11 : FROM ${METRICS_IMAGE} as metrics', '\\n']"}
```

[k8s_installer_build.log](https://github.com/IntelAI/nauta/files/2942409/k8s_installer_build.log)

**Comment by ajoskowski** [comment]
It looks like problem with building of "nauta/shared/build/metrics" image, which is a dependency of "nauta/batch-inference" image. Please pull new changes from develop brach and later run the following commands:
- `make k8s-installer-clean`
- `make k8s-installer-build`

**Comment by micossow** [comment]
It still fails with a slightly different error:
```
fatal: [local]: FAILED! => {"ansible_job_id": "981770493062.6474", "attempts": 1, "changed": false, "finished": 1, "msg": "Error pulling image nauta/nauta/registry:2.6.2 - 404 Client Error: Not Found (\"pull access denied for nauta/nauta/registry, repository does not exist or may require 'docker login'\")"}
```
commit: de1253ae8ccff02721bea0c648f0ca9c17b76b6e
[k8s_installer_build.log](https://github.com/IntelAI/nauta/files/2944940/k8s_installer_build.log)

**Comment by micossow** [comment]
Fixed by rebuilding after deleting `tools/.workspace` and running `docker system prune`
