### ISSUE TITLE
Terraform Error - Nauta on Google Cloud Platform

### ISSUE THREAD

**Issue by timoei** [IntelAI/nauta#8]
Hi,

I was trying to install Nauta on GCP when a terraform error occurred. I used the last beta release of Nauta and followed the [Gettinge Started Guide](https://github.com/IntelAI/nauta/blob/develop/toolbox/providers/gcp/gcp.md). 

This is the last output of the script: 
[error_message.txt](https://github.com/IntelAI/nauta/files/3013333/error_message.txt)

Any suggestions on how to fix it?

Thanks & BR
Timo

**Comment by waldekpi** [comment]
Hi Timo,
It looks that you have mismatch between configuration file (tf definitions, tfstate) and terraform binaries. Some syntax is not supported yet.

Please compare terraform version from your `/home/t_eichhorn87/nauta/.workspace/terraform/nauta/terraform.tfstate` file, `/home/t_eichhorn87/nauta/.bin/terraform` binary. Please let me know which version you have.

**Comment by timoei** [comment]
Hi,

`~/nauta/.bin$ ./terraform --version` outputs version: **Terraform v0.11.7**
And it seems like `/home/t_eichhorn87/nauta/.workspace/terraform/nauta/terraform.tfstate` is an empty file. Where can I check the version of this? 

> ~/nauta/.workspace/terraform/nauta$ ls -l
total 24
-rw-rw-r-- 1 5291 Mar 27 13:50 main.tf
-rw-rw-r-- 1  932 Mar 27 13:50 output.tf
-rw------- 1 3272 Mar 27 13:50 private
-rw-rw-r-- 1  724 Mar 27 13:50 public
-rw-rw-r-- 1    0 Mar 27 13:50 terraform.tfstate
-rw-rw-r-- 1  901 Mar 27 13:50 variables.tf

BR
Timo

**Comment by waldekpi** [comment]
I've checked this issue and reproduced it.

The question is that terraform uses google plugins underneath. It means that terraform version can be old, but package downloaded from the internet during the installation has the newest google provider version included.

Please build nauta from upstream version (terraform definition files are compatible with current google provider version).

**Comment by timoei** [comment]
This worked well, thanks!

**Comment by AdamTumi** [comment]
Solution provided and worked.
